# Generated by Django 2.2.2 on 2019-09-06 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Carro', 'verbose_name_plural': 'Carros'},
        ),
        migrations.AlterModelOptions(
            name='log',
            options={'verbose_name': 'Registro', 'verbose_name_plural': 'Registros'},
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'verbose_name': 'Dono', 'verbose_name_plural': 'Donos'},
        ),
        migrations.AlterField(
            model_name='log',
            name='departure_time',
            field=models.DateTimeField(blank=True, verbose_name='Horário de saída'),
        ),
    ]
