# Generated by Django 2.2.2 on 2019-09-06 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20190905_2336'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='color',
            field=models.CharField(default=' ', max_length=30, verbose_name='Cor'),
        ),
        migrations.AddField(
            model_name='car',
            name='description',
            field=models.TextField(default=' ', max_length=10000, verbose_name='Descrição'),
        ),
    ]
