# Generated by Django 2.2.2 on 2019-09-06 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190906_1917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='color',
            field=models.CharField(max_length=30, verbose_name='Cor'),
        ),
        migrations.AlterField(
            model_name='car',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Descrição'),
        ),
    ]
