# Generated by Django 2.2.2 on 2019-10-06 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190908_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='instituition',
            field=models.CharField(default='IFMS - Campus Dourados', max_length=50, verbose_name='Instituição'),
            preserve_default=False,
        ),
    ]
